### ISSUE TITLE
mac m1 not work?

### ISSUE THREAD

**Issue by ljshwyykl** [near/near-sdk-tools#4]
mac m1 not work?

https://github.com/near/near-sdk-tools/blob/master/npm/getBinary.js#L14
```
    if (type === 'Linux' && arch === 'x64') return 'Linux';
    if (type === 'Darwin' && arch === 'x64') return 'Darwin';
```

and mac m1 
```
type === 'Darwin' and arch === 'arm64'
```
not work?

**Comment by JuEnPeHa** [comment]
> mac m1 not work?
> 
> https://github.com/near/near-sdk-tools/blob/master/npm/getBinary.js#L14
> 
> ```
>     if (type === 'Linux' && arch === 'x64') return 'Linux';
>     if (type === 'Darwin' && arch === 'x64') return 'Darwin';
> ```
> 
> and mac m1
> 
> ```
> type === 'Darwin' and arch === 'arm64'
> ```
> 
> not work?

Hello, same problem here, there is no plan to fix it?, thank you.

**Comment by frol** [comment]
near-sdk-tools are soft-deprecated. Consider using https://github.com/near/workspaces
